#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Usage:
  bloat_survey [options] CSVFILE
  bloat_survey -h | --help | -V | --version

Options:
    -h            Display this help info
    -v,--verbose  Provide more verbose output
"""
import os
import re
import csv
import sys
import datetime
import statistics as stats
from docopt import docopt
from loguru import logger as log
from tqdm import tqdm

def number_profile(values):
    """
    Given a list of numerical values, compute some basic stats on them.
    """
    minv = min(values)
    maxv = max(values)
    avgv = stats.mean(values)
    medv = stats.median(values)
    return minv,medv,avgv,maxv

def assess_file(fname):
    """
    Load a CSV file and scan it for bloat signals.
    """
    record_times_count = {}
    satellite_times_count = {}

    linecount = -1
    with open(fname,'r') as fh:
        for i,line in enumerate(fh):
            pass
        linecount = i+1

    with open(fname, 'r') as fcsv:
        reader = csv.DictReader(fcsv,delimiter=',')
        for row in tqdm(reader,total=linecount):
            user = row['user_id']
            rec_time = row['record_time']
            sat_time = row['satellite_time']
            rkey = (user,rec_time)
            skey = (user,sat_time)
            record_times_count[rkey] = record_times_count.get(rkey, 0) + 1
            satellite_times_count[skey] = satellite_times_count.get(skey, 0) + 1

    # report basic counts
    num_rec = len(record_times_count.keys())
    num_sat = len(satellite_times_count.keys())
    print(f"Num unique record_times: {num_rec:,}")
    print(f"Num unique satellite_times: {num_sat:,}")
    print(f"Record_time field has {100*num_rec/float(num_sat)-100:0.2f}% more records.")

    # report stats on key value repetitions
    print(f"Field Min#  Med#  Avg#  Max#")
    minv,medv,avgv,maxv = number_profile(record_times_count.values())
    print(f"RecTm {minv:0.1f}   {medv:0.1f}    {avgv:0.1f} {maxv:0.1f}")
    minv,medv,avgv,maxv = number_profile(satellite_times_count.values())
    print(f"SatTm {minv:0.1f}   {medv:0.1f}    {avgv:0.1f} {maxv:0.1f}")


if __name__ == '__main__':
    args = docopt(__doc__, version='0.1.1')

    loglevel = "INFO"
    csvfname = args['CSVFILE']

    assess_file(csvfname)
