#!/bin/bash
#SBATCH --account=def-dfuller
#SBATCH --job-name=sniff-conflict-ssk-w1-gps
#SBATCH --output=conflict-report-ssk-w1-gps.out
#SBATCH --time=00:30:00
#SBATCH --mem=40G
./bloat_survey Telemetry/ssk-w1-gps.csv 
