#!/bin/bash
#SBATCH --account=def-dfuller
#SBATCH --job-name=sniff-conflict-ssk-w1-accel
#SBATCH --output=conflict-report-ssk-w1-accel.out
#SBATCH --time=12:00:00
#SBATCH --mem=40G
./bloat_survey Telemetry/ssk-w1-accel.csv 
